name: CI-Client

on:
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "client/**"

defaults:
  run:
    working-directory: client

jobs:
  checks:
    runs-on: ubuntu-latest
    container: node:22-alpine
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npx vite build
